-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 22:49:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Wavedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Wavedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Wavedb` DEFAULT CHARACTER SET utf8 ;
USE `Wavedb` ;

-- -----------------------------------------------------
-- Table `Wavedb`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wavedb`.`classes` ;

CREATE TABLE IF NOT EXISTS `Wavedb`.`classes` (
  `classId` INT NOT NULL,
  `className` VARCHAR(50) NULL,
  `classType` VARCHAR(50) NULL,
  `ageBegin` INT NULL,
  `ageEnd` INT NULL,
  `coach` VARCHAR(50) NULL,
  `time` TIME(2) NULL,
  `dayOfWeek` VARCHAR(15) NULL,
  `classSize` INT NULL,
  `coed` TINYINT NULL,
  `length` INT(3) NULL,
  `price` DECIMAL NULL,
  `desc` VARCHAR(140) NULL,
  PRIMARY KEY (`classId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wavedb`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wavedb`.`account` ;

CREATE TABLE IF NOT EXISTS `Wavedb`.`account` (
  `accountId` INT NOT NULL,
  `accountType` VARCHAR(7) NULL,
  `email` VARCHAR(45) NULL,
  `phone` INT(10) NULL,
  `econtact` VARCHAR(45) NULL,
  `econtactPhone` INT(10) NULL,
  `notes` VARCHAR(140) NULL,
  `fname` VARCHAR(20) NULL,
  `lname` VARCHAR(20) NULL,
  `address` VARCHAR(50) NULL,
  `username` VARCHAR(20) NULL,
  `password` VARCHAR(45) NULL,
  `accountBalance` DECIMAL NULL,
  PRIMARY KEY (`accountId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wavedb`.`child`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wavedb`.`child` ;

CREATE TABLE IF NOT EXISTS `Wavedb`.`child` (
  `fname` VARCHAR(20) NULL,
  `lname` VARCHAR(20) NULL,
  `childId` INT NOT NULL,
  `dob` DATE NULL,
  `notes` VARCHAR(140) NULL,
  PRIMARY KEY (`childId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wavedb`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wavedb`.`Events` ;

CREATE TABLE IF NOT EXISTS `Wavedb`.`Events` (
  `dateEvent` DATE NULL,
  `desc` VARCHAR(140) NULL,
  `price` DECIMAL NULL,
  `time` TIME(2) NULL,
  `coach` VARCHAR(20) NULL,
  `size` INT NULL,
  `length` TIME(2) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wavedb`.`childToAccount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wavedb`.`childToAccount` ;

CREATE TABLE IF NOT EXISTS `Wavedb`.`childToAccount` (
  `childIdTransfer` INT NULL,
  `accountIdTransfer` INT NULL,
  INDEX `childIdTransfer_idx` (`childIdTransfer` ASC),
  INDEX `accountIdTransfer_idx` (`accountIdTransfer` ASC),
  CONSTRAINT `childIdTransfer`
    FOREIGN KEY (`childIdTransfer`)
    REFERENCES `Wavedb`.`child` (`childId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `accountIdTransfer`
    FOREIGN KEY (`accountIdTransfer`)
    REFERENCES `Wavedb`.`account` (`accountId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
